name: ensambler
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.7
  - nomkl
  - numpy==1.16.1
  - pandas==0.25.2
  - scikit-learn==0.23.1
  - scipy==1.4.1
  - statsmodels==0.11.1
  - lightgbm==2.3.1
  - patsy==0.5.1
  - threadpoolctl
  - seaborn
  - xgboost==0.90
  - s3fs
  - boto3
  - cvxpy
  - dask
  - matplotlib==3.2.1
  - tqdm==4.46.0
  - pylint
  - pyyaml
  - pip
  - pytest-cov
  - rpy2
  - r-base<4.0
  - r-forecast
  - r-data.table
  - r-tsfeatures
  - jupyterlab
  - optuna
  - pytorch==1.4.0
  - xlrd
  - pip:
    - tsfeatures==0.1.0
